export const FETCHING_DATA = 'FETCHING_DATA';
export const FETCHING_DATA_SUCCESS = 'FETCHING_DATA_SUCCESS';
export const FETCHING_DATA_ERROR = 'FETCHING_DATA_ERROR';
export const FETHING_PRICE = 'FETCHING_PRICE';
export const FETCHING_PRICE_SUCCESS = 'FETCHING_PRICE_SUCCESS';
export const SHOW_MORE = 'SHOW_MORE';